package com.hse.recommendationsystem.domain.service.stubs

import com.hse.recommendationsystem.domain.model.MatchType
import com.hse.recommendationsystem.domain.model.RfqCore
import com.hse.recommendationsystem.domain.model.SupplierRecommendationCandidate
import com.hse.recommendationsystem.domain.service.SupplierRecommendationEngine
import org.springframework.stereotype.Component
import java.util.UUID

@Component
class MockRecommendationEngine : SupplierRecommendationEngine {
    override fun recommendForAcceptedRfq(rfq: RfqCore): List<SupplierRecommendationCandidate> =
        MOCK_SUPPLIERS.map { template ->
            template.copy(
                // Tie mock output to RFQ id for traceability in demos
                description = "${template.description} (rfq=${rfq.rfqId})",
            )
        }

    companion object {
        const val MOCK_MODEL_VERSION = "mock-ranking-v1"

        private val MOCK_SUPPLIERS =
            listOf(
                SupplierRecommendationCandidate(
                    supplierId = UUID.fromString("a1000000-0000-4000-8000-000000000001"),
                    unifiedSupplierId = UUID.fromString("b1000000-0000-4000-8000-000000000001"),
                    matchType = MatchType.MATCH,
                    modelVersion = MOCK_MODEL_VERSION,
                    customerInNeed = true,
                    isCustomer = true,
                    name = "Nordic Components GmbH",
                    website = "https://nordic-components.example",
                    profileUrl = "https://marketplace.example/suppliers/nordic-components",
                    country = "DE",
                    distributionArea = "EU",
                    description = "Industrial fasteners and sheet metal.",
                    descriptionDe = "Industriebefestigung und Blechbearbeitung.",
                    descriptionEn = "Industrial fasteners and sheet metal.",
                    supplierTypes = listOf("Manufacturer", "Distributor"),
                    products = listOf("Bolts", "Brackets"),
                    keywords = listOf("fasteners", "CNC"),
                    productCategories = listOf("Mechanical parts"),
                ),
                SupplierRecommendationCandidate(
                    supplierId = UUID.fromString("a1000000-0000-4000-8000-000000000002"),
                    unifiedSupplierId = UUID.fromString("b1000000-0000-4000-8000-000000000002"),
                    matchType = MatchType.MATCH,
                    modelVersion = MOCK_MODEL_VERSION,
                    customerInNeed = true,
                    isCustomer = true,
                    name = "Alpine Precision AG",
                    website = "https://alpine-precision.example",
                    profileUrl = "https://marketplace.example/suppliers/alpine-precision",
                    country = "CH",
                    distributionArea = "DACH",
                    description = "High-precision machining and assemblies.",
                    descriptionDe = "Hochpräzisionsbearbeitung.",
                    descriptionEn = "High-precision machining and assemblies.",
                    supplierTypes = listOf("Manufacturer"),
                    products = listOf("Shafts", "Housings"),
                    keywords = listOf("precision", "CNC"),
                    productCategories = listOf("Machining"),
                ),
                SupplierRecommendationCandidate(
                    supplierId = UUID.fromString("a1000000-0000-4000-8000-000000000003"),
                    unifiedSupplierId = UUID.fromString("b1000000-0000-4000-8000-000000000003"),
                    matchType = MatchType.WEAK_MATCH,
                    modelVersion = MOCK_MODEL_VERSION,
                    customerInNeed = true,
                    isCustomer = true,
                    name = "Baltic Supply OÜ",
                    website = "https://baltic-supply.example",
                    profileUrl = "https://marketplace.example/suppliers/baltic-supply",
                    country = "EE",
                    distributionArea = "Baltics",
                    description = "General industrial supply and logistics.",
                    descriptionDe = null,
                    descriptionEn = "General industrial supply and logistics.",
                    supplierTypes = listOf("Distributor"),
                    products = listOf("Bearings", "Seals"),
                    keywords = listOf("supply", "logistics"),
                    productCategories = listOf("Industrial supply"),
                ),
                SupplierRecommendationCandidate(
                    supplierId = UUID.fromString("a1000000-0000-4000-8000-000000000004"),
                    unifiedSupplierId = UUID.fromString("b1000000-0000-4000-8000-000000000004"),
                    matchType = MatchType.WEAK_MATCH,
                    modelVersion = MOCK_MODEL_VERSION,
                    customerInNeed = false,
                    isCustomer = true,
                    name = "Central Europe Parts s.r.o.",
                    website = "https://ce-parts.example",
                    profileUrl = "https://marketplace.example/suppliers/ce-parts",
                    country = "CZ",
                    distributionArea = "EU",
                    description = "Wholesale mechanical components.",
                    descriptionDe = "Großhandel mechanische Komponenten.",
                    descriptionEn = "Wholesale mechanical components.",
                    supplierTypes = listOf("Wholesaler"),
                    products = listOf("Gears", "Pulleys"),
                    keywords = listOf("wholesale", "components"),
                    productCategories = listOf("Power transmission"),
                ),
                SupplierRecommendationCandidate(
                    supplierId = UUID.fromString("a1000000-0000-4000-8000-000000000005"),
                    unifiedSupplierId = UUID.fromString("b1000000-0000-4000-8000-000000000005"),
                    matchType = MatchType.RELATED,
                    modelVersion = MOCK_MODEL_VERSION,
                    customerInNeed = true,
                    isCustomer = true,
                    name = "Iberia Metalworks SL",
                    website = "https://iberia-metalworks.example",
                    profileUrl = "https://marketplace.example/suppliers/iberia-metalworks",
                    country = "ES",
                    distributionArea = "Iberia",
                    description = "Metal fabrication and coatings.",
                    descriptionDe = null,
                    descriptionEn = "Metal fabrication and coatings.",
                    supplierTypes = listOf("Manufacturer"),
                    products = listOf("Frames", "Panels"),
                    keywords = listOf("fabrication", "coating"),
                    productCategories = listOf("Fabrication"),
                ),
                SupplierRecommendationCandidate(
                    supplierId = UUID.fromString("a1000000-0000-4000-8000-000000000006"),
                    unifiedSupplierId = UUID.fromString("b1000000-0000-4000-8000-000000000006"),
                    matchType = MatchType.RELATED,
                    modelVersion = MOCK_MODEL_VERSION,
                    customerInNeed = false,
                    isCustomer = true,
                    name = "North Sea Engineering BV",
                    website = "https://north-sea-eng.example",
                    profileUrl = "https://marketplace.example/suppliers/north-sea-eng",
                    country = "NL",
                    distributionArea = "Benelux",
                    description = "Marine and industrial engineering services.",
                    descriptionDe = null,
                    descriptionEn = "Marine and industrial engineering services.",
                    supplierTypes = listOf("Service provider"),
                    products = listOf("Welding", "Inspection"),
                    keywords = listOf("marine", "engineering"),
                    productCategories = listOf("Services"),
                ),
                SupplierRecommendationCandidate(
                    supplierId = UUID.fromString("a1000000-0000-4000-8000-000000000007"),
                    unifiedSupplierId = UUID.fromString("b1000000-0000-4000-8000-000000000007"),
                    matchType = MatchType.NO_MATCH,
                    modelVersion = MOCK_MODEL_VERSION,
                    customerInNeed = false,
                    isCustomer = true,
                    name = "Mediterranean Plastics SA",
                    website = "https://med-plastics.example",
                    profileUrl = "https://marketplace.example/suppliers/med-plastics",
                    country = "IT",
                    distributionArea = "EU",
                    description = "Plastic injection molding for consumer goods.",
                    descriptionDe = null,
                    descriptionEn = "Plastic injection molding for consumer goods.",
                    supplierTypes = listOf("Manufacturer"),
                    products = listOf("Casings", "Covers"),
                    keywords = listOf("plastics", "injection"),
                    productCategories = listOf("Polymers"),
                ),
                SupplierRecommendationCandidate(
                    supplierId = UUID.fromString("a1000000-0000-4000-8000-000000000008"),
                    unifiedSupplierId = UUID.fromString("b1000000-0000-4000-8000-000000000008"),
                    matchType = MatchType.NO_MATCH,
                    modelVersion = MOCK_MODEL_VERSION,
                    customerInNeed = false,
                    isCustomer = true,
                    name = "Scandinavian Packaging AB",
                    website = "https://scan-packaging.example",
                    profileUrl = "https://marketplace.example/suppliers/scan-packaging",
                    country = "SE",
                    distributionArea = "Nordics",
                    description = "Packaging materials and labeling.",
                    descriptionDe = null,
                    descriptionEn = "Packaging materials and labeling.",
                    supplierTypes = listOf("Distributor"),
                    products = listOf("Boxes", "Labels"),
                    keywords = listOf("packaging", "labels"),
                    productCategories = listOf("Packaging"),
                ),
            )
    }
}